a, b = map(int, input("НАПИШИТЕ ЧИСЛО ПЖ").split())
print(a - b)
print("aboba")
print("myak")
print("selihova lubov")
print("я сижу в этой столовой уже 25 лет")
print("пережевывая этот монотонный винегрет")
print("и я слышу только:")
print("ешь, ешь, ешь, что дают!")
print("устрой дестрой, порядок это отстой")